analytics.onpremise.enable=false
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 1089441,\\n  \\"name\\"\: \\"OrangeHRM Automation - Liliana Fajardo\\",\\n  \\"teamId\\"\: 1074594,\\n  \\"organizationId\\"\: 1128645,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 1074594\\n}"
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=false
analytics.testcloud.hub.switchHub.enable=false
