<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dashboard</name>
   <tag></tag>
   <elementGuidId>c457837b-c3ab-4bf3-be71-00497a5a5e88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/aside/nav/div[2]/ul/li[8]/a/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class='oxd-text oxd-text--span oxd-main-menu-item--name' and text()='Dashboard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.oxd-main-menu-item.active > span.oxd-text.oxd-text--span.oxd-main-menu-item--name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ddad69df-8abe-474b-84db-5edb713ea87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-text oxd-text--span oxd-main-menu-item--name</value>
      <webElementGuid>5569b407-1585-49b5-b36d-e36ff9a715e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>ed46db46-3561-41fe-88b4-9eb4352bda44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='oxd-text oxd-text--span oxd-main-menu-item--name' and text()='Dashboard']</value>
      <webElementGuid>f7744904-0037-4d48-9ce8-a70eb52e9d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/aside/nav/div[2]/ul/li[8]/a/span</value>
      <webElementGuid>16a432a0-c7f3-4d4c-b95f-c1e7c0b0a8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>7d77ac3b-df65-4375-bd51-a83aca0e3f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/span</value>
      <webElementGuid>2737f5c3-3be4-493e-9679-2cd4491db613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>d99ee04e-1351-42fd-ab22-c9c902a20858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
