<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ToDate</name>
   <tag></tag>
   <elementGuidId>312f0138-a570-4c32-8543-35e9b9ee6aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[2]/form/div/div/div[2]/div/div[2]/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//label[text()='To Date']/ancestor::div[contains(@class,'oxd-input-group')]//input[@placeholder='yyyy-dd-mm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>49b1784d-d558-4e93-8bde-e17686251819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-icon bi-calendar oxd-date-input-icon</value>
      <webElementGuid>24f0d129-acd9-496e-a37f-3337f96643ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[text()='To Date']/ancestor::div[contains(@class,'oxd-input-group')]//input[@placeholder='yyyy-dd-mm']</value>
      <webElementGuid>ee2c988d-f40b-4b98-a1d0-94c04774c13f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[2]/form/div/div/div[2]/div/div[2]/div/div/i</value>
      <webElementGuid>571f6674-5cdd-4542-9187-af8cb86422bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/i</value>
      <webElementGuid>56a34335-e2e9-41a6-b2dc-95487cd0801b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
