<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Schedule InterviewCandidateVacancyHirin_bd7d94_1</name>
   <tag></tag>
   <elementGuidId>3fc54c47-bbf2-4196-9467-4b9c5d094960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.oxd-layout-context</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>964a17d9-3e59-4c94-a49d-5902cd62a6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-layout-context</value>
      <webElementGuid>0a59a378-6308-46a8-979e-f6e3002766c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Schedule InterviewCandidateVacancyHiring ManagerCurrent StatusInterview TitleInterviewer Add Another DateTimeNotes * Required Cancel  Save </value>
      <webElementGuid>a194e397-bbe7-417e-9a63-631d4bf42582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout orangehrm-upgrade-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]</value>
      <webElementGuid>ceb6279d-ec5c-4688-b212-560bd1f3a36c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]</value>
      <webElementGuid>8bfe85a0-0bbc-4f25-a056-6c406f111be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>f33a1872-7059-4c21-ae04-536ce33dbbdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Schedule InterviewCandidateVacancyHiring ManagerCurrent StatusInterview TitleInterviewer Add Another DateTimeNotes * Required Cancel  Save ' or . = 'Schedule InterviewCandidateVacancyHiring ManagerCurrent StatusInterview TitleInterviewer Add Another DateTimeNotes * Required Cancel  Save ')]</value>
      <webElementGuid>c02bc504-06d1-4b38-acbe-76261226a1f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
