<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Schedule InterviewCandidateVacancyHirin_bd7d94</name>
   <tag></tag>
   <elementGuidId>bd5c1be5-241f-40c7-aea5-4aab0b27702d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-card-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2cffea70-9dca-403c-ba92-7897d621abf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-card-container</value>
      <webElementGuid>34628574-d0cf-4c31-83b5-622d229fa5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Schedule InterviewCandidateVacancyHiring ManagerCurrent StatusInterview TitleInterviewer Add Another DateTimeNotes * Required Cancel  Save </value>
      <webElementGuid>ea6984c1-20de-417e-814e-1c3f8286dafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout orangehrm-upgrade-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]</value>
      <webElementGuid>7d66a3b0-39ce-4b66-858b-b9111fcd2e03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div</value>
      <webElementGuid>10a291a3-81ba-4db6-b5f4-38c45a6e483f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>dc1a4332-5c62-4a42-9c71-fc1623a60464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Schedule InterviewCandidateVacancyHiring ManagerCurrent StatusInterview TitleInterviewer Add Another DateTimeNotes * Required Cancel  Save ' or . = 'Schedule InterviewCandidateVacancyHiring ManagerCurrent StatusInterview TitleInterviewer Add Another DateTimeNotes * Required Cancel  Save ')]</value>
      <webElementGuid>f0113794-48f5-4ebd-a824-8f2a135e7c27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
